name: Lint Codebase

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Run ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'
                  cache-dependency-path: |
                      package.json
                      pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install

            - name: Run Linter
              run: pnpm lint
